### ISSUE TITLE
Complete code release

### ISSUE THREAD

**Issue by j-min** [wenhuchen/Meta-Module-Network#1]
Hi, do you plan to update the code?
I can't find the implementations of three core parts of the model: visual encoder, program generator and meta modules. ex) where is `Networks.py` referred in `generatre_program.py`?

**Comment by wenhuchen** [comment]
Did you see go into the code/ folder and download the file: Please download the code from "https://drive.google.com/open?id=14sKn_163FYqTVInV6OL_ZukT2wp2uPtn". All the necessary code for replicating the test-set result is here.

**Comment by j-min** [comment]
I thought the grdive files are only for evaluation, as written in readme files.
I just downloaded the code from the gdrive and found the model codes. thanks!
