### ISSUE TITLE
Coarse-to-fine Parser

### ISSUE THREAD

**Issue by ayushjain1144** [wenhuchen/Meta-Module-Network#2]
Hi, 

Thank you for your awesome work. 

From `generate_programs.py` I understood that you are using a normal Seq2Seq Parser. Could you let me know if you have open-sourced the Coarse2Fine Parser Implementation so that I can replicate your parsing results described in the paper on my own data?

Thanks

PS: I have downloaded the google drive which has the model files and data.

**Comment by dreichCSL** [comment]
Were you actually able to train and run the program parser? It looks like the code for training in generate_programs.py is incomplete and there is also no trained parser model provided to actually parse the questions. Am I missing something here?

Thanks
