### ISSUE TITLE
where does gqa_visual_features.zip come from?

### ISSUE THREAD

**Issue by sjtuytc** [wenhuchen/Meta-Module-Network#3]
Hi, I notice that you use a customized version of gqa visual feature. How does it come from?
I cannot download it because Read error at byte 38950928384/174855185539 (Connection reset by peer). Giving up.

**Comment by wenhuchen** [comment]
The features are stored in Microsoft Azure Server, @linjieli222 could you answer his question?

**Comment by linjieli222** [comment]
Hi, 

I just checked the connection, there is no problem. I was able to download the features within 50 minutes via `wget`:
![image](https://user-images.githubusercontent.com/12926026/108921445-344a9700-75eb-11eb-9a5b-8c4dceb096ee.png)

The features are extracted using [Bottom-up attention](https://github.com/peteanderson80/bottom-up-attention).

**Comment by sjtuytc** [comment]
Thank you very much!

**Comment by sjtuytc** [comment]
> Hi,
> 
> I just checked the connection, there is no problem. I was able to download the features within 50 minutes via `wget`:
> ![image](https://user-images.githubusercontent.com/12926026/108921445-344a9700-75eb-11eb-9a5b-8c4dceb096ee.png)
> 
> The features are extracted using [Bottom-up attention](https://github.com/peteanderson80/bottom-up-attention).

I've tried in my Chinese server, the same error happened again. Do you test use your internal web connection? I guess we cannot download it from outside.

**Comment by linjieli222** [comment]
> > Hi,
> 
> > 
> 
> > I just checked the connection, there is no problem. I was able to download the features within 50 minutes via `wget`:
> 
> > ![image](https://user-images.githubusercontent.com/12926026/108921445-344a9700-75eb-11eb-9a5b-8c4dceb096ee.png)
> 
> > 
> 
> > The features are extracted using [Bottom-up attention](https://github.com/peteanderson80/bottom-up-attention).
> 
> 
> 
> I've tried in my Chinese server, the same error happened again. Do you test use your internal web connection? I guess we cannot download it from outside.

The connection is public. You should be getting a "404" error if the connection is private. From what you mentioned in your initial post, looks like it is an internet speed issue.

**Comment by sjtuytc** [comment]
Thanks. I successfully downloaded it.
