### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by gitzyong812** [wenhuchen/Meta-Module-Network#6]
Thanks for opening the code!  
I think your work on preprocessing GQA programs is very necessary.
This is a crutial step for practical visual reasoning on natural images.  I decide to follow this work. 
For convenience of followers, could you please provide your pretrained models (especially for the program generator)?

**Comment by wenhuchen** [comment]
You can follow the README to train it by yourself, it only takes within a few hours:
Using NL2Program Model to Predict Test-Dev Programs from input questions:
Train the sequence-2-sequence model:
  python generate_program.py --do_preprocess
Evaluate the NL2Program
  python generate_program.py --do_testdev
Prepare the generated programs for the modular transformer
  python generate_program.py --do_trainval_unbiased
