### ISSUE TITLE
Code for CLEVR experiments?

### ISSUE THREAD

**Issue by ikb-a** [wenhuchen/Meta-Module-Network#7]
Hi, I wanted to ask, is there any chance that the code for the preliminary CLEVR experiments mentioned in the paper could be released? Thanks for your time!

**Comment by wenhuchen** [comment]
The setup is almost the same, just the API functions are slightly different. It's been a while since I ran these experiments, pretty hard to find a runnable version. Sorry about that.

**Comment by ikb-a** [comment]
No worries; thanks for your time!
