### ISSUE TITLE
Code for extracting features from Bottom up attention

### ISSUE THREAD

**Issue by sumit-agrwl** [wenhuchen/Meta-Module-Network#8]
Can you please provide the code for extracting features using bottom up code? I am working on a small subset of images and want to replicate the numpy files that you have used as features?

**Comment by wenhuchen** [comment]
@linjieli222

**Comment by linjieli222** [comment]
@sumit-agrwl We follow the same script used in [UNITER](https://github.com/ChenRocks/UNITER) to extract the image features. Check out the step 6 in [Quick Start](https://github.com/ChenRocks/UNITER#quick-start). Note that the docker for the script [extract_imgfeat.sh](https://github.com/ChenRocks/UNITER/blob/master/scripts/extract_imgfeat.sh) is built with caffe that is compatible only with older cuda drivers.

**Comment by linjieli222** [comment]
If it is hard to downgrade your cuda driver to be compatible with the docker, there are a lot of alternative pytorch bottom-up attention repos, such as https://github.com/MILVLG/bottom-up-attention.pytorch, which might not give you the features that is exactly the same as what we have provided, but the quality of these features should be comparable or even better.

**Comment by linjieli222** [comment]
More details about the docker are explained in this issue: https://github.com/ChenRocks/UNITER/issues/18
